name: test_git_action #OK

on:
  push:
    branches: [ main ] #if (push => main) {déclenche run>git action>workflow}

jobs:
  test_git_action:
    runs-on: ubuntu-latest #Image Docker pour ./workflow
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 #tout récuperer
      - name: Launch .sh
        run: ./.github/coding-style.sh . .
      - name: Check file
        run: |
          if [[ -s coding-style-reports.log ]]
          then
            echo "Coding Style dans le report.log"
            exit 1
          else
            echo "Aucune Coding Style dans le report.log"
            exit 0
          fi
